version: "3.8"

services:
  nginx-rtmp-prod:
    build: .
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./logs:/var/log/nginx
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    runtime: nvidia

  nginx-rtmp-local:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx-local.conf:/usr/local/nginx/conf/nginx.conf
      - ./stat.xsl:/usr/local/nginx/html/stat.xsl
      - ./logs:/var/log/nginx
