services:
  nginx-rtmp:
    build: .
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./logs:/var/log/nginx
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg # Mount host's ffmpeg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
