services:
  nginx-rtmp:
    build: .
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./logs:/var/log/nginx
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg # Mount host's ffmpeg
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    runtime: nvidia
